version: '3'

services:
  app:
    container_name: app
    build: .docker/app
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    ports:
      - '8080:80'
    expose:
      - '8080'
    depends_on:
      - mysql
      - elasticsearch
    links:
      - mysql
      - elasticsearch

  mysql:
    container_name: mysql
    image: mysql:8
    environment:
      MYSQL_DATABASE: technical_test_phalcon_app
      MYSQL_ROOT_PASSWORD: root
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - .docker/mysql/data:/var/lib/mysql
      - .docker/mysql/scripts:/scripts
    ports:
      - '3306:3306'

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.4.0
    container_name: elasticsearch
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    volumes:
      - .docker/elasticsearch/data:/usr/share/elasticsearch/data
      - .docker/elasticsearch/scripts:/scripts
    ports:
      - 9200:9200
